"""Generates the HeyGemini launcher icon: a four-point sparkle with a small companion.

Writes Android adaptive-icon vectors (light, dark, themed monochrome) and README
preview PNGs from one geometry, so every variant stays identical.
Run from the project root: python3 artwork/generate_icon.py
"""

from pathlib import Path

from PIL import Image, ImageDraw

RES = Path("app/src/main/res")
ARTWORK = Path("artwork")

# Geometry in the 108-unit adaptive icon viewport (safe zone: 66-unit circle).
MAIN_STAR = (52, 56, 25)  # center x, center y, tip radius
SMALL_STAR = (72, 35, 7.5)
PINCH = 0.13  # Control point offset as a share of the radius; lower = slimmer arms.
TIP_ROUNDING = 1.6  # Stroke width that rounds the tips.

GRADIENT = ("#45D0FF", "#2E6BFF")  # Top-left to bottom-right.
LIGHT_BG = ("#FFFFFF", "#EEF1F5")
# Neutral grey sampled from ColorOS's own dark icons (#2C2B2B -> #161616).
DARK_BG = ("#2E2E30", "#18181A")


def star_points(cx, cy, r):
    k = r * PINCH
    tips = [(cx, cy - r), (cx + r, cy), (cx, cy + r), (cx - r, cy)]
    controls = [(cx + k, cy - k), (cx + k, cy + k), (cx - k, cy + k), (cx - k, cy - k)]
    return tips, controls


def star_path(cx, cy, r):
    tips, controls = star_points(cx, cy, r)
    f = lambda v: f"{v:.2f}".rstrip("0").rstrip(".")
    parts = [f"M{f(tips[0][0])},{f(tips[0][1])}"]
    for i in range(4):
        (qx, qy), (ex, ey) = controls[i], tips[(i + 1) % 4]
        parts.append(f"Q{f(qx)},{f(qy)} {f(ex)},{f(ey)}")
    return "".join(parts) + "Z"


def gradient_attr(name, top_left, bottom_right, box):
    x0, y0, x1, y1 = box
    return f"""        <aapt:attr name="android:{name}">
            <gradient
                android:endColor="{bottom_right}"
                android:endX="{x1}"
                android:endY="{y1}"
                android:startColor="{top_left}"
                android:startX="{x0}"
                android:startY="{y0}"
                android:type="linear" />
        </aapt:attr>"""


def star_xml(star, colors):
    cx, cy, r = star
    box = (cx - r, cy - r, cx + r, cy + r)
    stroke = TIP_ROUNDING * r / MAIN_STAR[2]
    attrs = (
        f'        android:pathData="{star_path(cx, cy, r)}"\n'
        f'        android:strokeLineJoin="round"\n'
        f'        android:strokeWidth="{stroke:.2f}"'
    )
    if colors is None:  # Monochrome mask.
        return f'    <path\n        android:fillColor="#FFFFFFFF"\n        android:strokeColor="#FFFFFFFF"\n{attrs} />'
    return (
        f"    <path\n{attrs}>\n"
        + gradient_attr("fillColor", *colors, box)
        + "\n"
        + gradient_attr("strokeColor", *colors, box)
        + "\n    </path>"
    )


def vector(body, comment):
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {comment} Generated by artwork/generate_icon.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
{body}
</vector>
"""


def background_body(top, bottom):
    return (
        '    <path android:pathData="M0,0h108v108h-108z">\n'
        + gradient_attr("fillColor", top, bottom, (54, 0, 54, 108))
        + "\n    </path>"
    )


def hex_rgb(value):
    value = value.lstrip("#")
    return tuple(int(value[i : i + 2], 16) for i in (0, 2, 4))


def lerp(a, b, t):
    return tuple(round(x + (y - x) * t) for x, y in zip(a, b))


def render_png(bg, size=512):
    """README preview: rounded square showing the central 72 units, like a launcher mask."""
    scale = 4
    canvas = size * scale
    crop, unit = 18, canvas / 72
    p = lambda v: (v - crop) * unit

    top, bottom = hex_rgb(bg[0]), hex_rgb(bg[1])
    image = Image.new("RGBA", (canvas, canvas))
    draw = ImageDraw.Draw(image)
    for row in range(canvas):
        draw.line([(0, row), (canvas, row)], fill=lerp(top, bottom, row / (canvas - 1)) + (255,))

    start, end = hex_rgb(GRADIENT[0]), hex_rgb(GRADIENT[1])
    for star in (MAIN_STAR, SMALL_STAR):
        cx, cy, r = star
        tips, controls = star_points(cx, cy, r)
        outline = []
        for i in range(4):
            (sx, sy), (qx, qy), (ex, ey) = tips[i], controls[i], tips[(i + 1) % 4]
            for step in range(48):
                t = step / 48
                outline.append((
                    p((1 - t) ** 2 * sx + 2 * (1 - t) * t * qx + t * t * ex),
                    p((1 - t) ** 2 * sy + 2 * (1 - t) * t * qy + t * t * ey),
                ))
        mask = Image.new("L", (canvas, canvas), 0)
        ImageDraw.Draw(mask).polygon(outline, fill=255)
        width = round(TIP_ROUNDING * r / MAIN_STAR[2] * unit)
        ImageDraw.Draw(mask).line(outline + outline[:1], fill=255, width=width, joint="curve")

        # Diagonal gradient over the star's box, matching the vector's start/end points.
        steps = 64
        swatch = Image.new("RGBA", (steps, steps))
        for x in range(steps):
            for y in range(steps):
                swatch.putpixel((x, y), lerp(start, end, (x + y) / (2 * steps - 2)) + (255,))
        x0, y0, side = round(p(cx - r)), round(p(cy - r)), round(2 * r * unit)
        fill = Image.new("RGBA", (canvas, canvas))
        fill.paste(swatch.resize((side, side), Image.BILINEAR), (x0, y0))
        # Extend edge colors under the rounded tips that poke past the box.
        image.paste(fill, (0, 0), Image.composite(mask, Image.new("L", mask.size, 0), fill.getchannel("A")))

    mask = Image.new("L", (canvas, canvas), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, canvas - 1, canvas - 1], radius=canvas * 0.22, fill=255)
    image.putalpha(mask)
    return image.resize((size, size), Image.LANCZOS)


def main():
    stars = lambda colors: star_xml(MAIN_STAR, colors) + "\n" + star_xml(SMALL_STAR, colors)
    files = {
        "drawable/ic_launcher_background.xml": vector(background_body(*LIGHT_BG), "Light icon background."),
        "drawable-night/ic_launcher_background.xml": vector(background_body(*DARK_BG), "Dark icon background."),
        "drawable/ic_launcher_foreground.xml": vector(stars(GRADIENT), "Sparkle artwork."),
        "drawable/ic_launcher_monochrome.xml": vector(stars(None), "Themed icon mask; the launcher tints it."),
    }
    for path, content in files.items():
        target = RES / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)

    render_png(LIGHT_BG).save(ARTWORK / "icon-light.png")
    render_png(DARK_BG).save(ARTWORK / "icon-dark.png")


if __name__ == "__main__":
    main()
